CREATE SCHEMA IF NOT EXISTS pim_schema;
CREATE SCHEMA IF NOT EXISTS shared_schema;
CREATE SCHEMA IF NOT EXISTS catalog_schema;
CREATE SCHEMA IF NOT EXISTS inventory_schema;
CREATE SCHEMA IF NOT EXISTS oms_schema;
