// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using engine_b.Common.Infrastructure.Data;

#nullable disable

namespace engine_b.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413175122_CRMInteractionsUpdate")]
    partial class CRMInteractionsUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("engine_b.Modules.CRM.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlacklistReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BlacklistedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BlacklistedBy")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBlacklisted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastOrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ReturnRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer");

                    b.Property<int>("Segment")
                        .HasColumnType("integer");

                    b.Property<int>("TotalOrders")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Wilaya")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Phone");

                    b.HasIndex("Segment");

                    b.ToTable("customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000001"),
                            City = "Alger",
                            CreatedAt = new DateTime(2025, 10, 15, 17, 51, 21, 893, DateTimeKind.Utc).AddTicks(9880),
                            Email = "amina@example.com",
                            FullName = "Amina Benali",
                            IsBlacklisted = false,
                            LastOrderDate = new DateTime(2026, 4, 11, 17, 51, 21, 893, DateTimeKind.Utc).AddTicks(9880),
                            Phone = "+213 0550 111 001",
                            ReturnRate = 5m,
                            RiskLevel = 0,
                            RiskScore = 15,
                            Segment = 2,
                            TotalOrders = 12,
                            TotalRevenue = 145000m,
                            Wilaya = 16
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000002"),
                            City = "Oran",
                            CreatedAt = new DateTime(2025, 12, 14, 17, 51, 21, 893, DateTimeKind.Utc).AddTicks(9880),
                            Email = "karim@example.com",
                            FullName = "Karim Hadj",
                            IsBlacklisted = false,
                            LastOrderDate = new DateTime(2026, 4, 3, 17, 51, 21, 893, DateTimeKind.Utc).AddTicks(9880),
                            Phone = "+213 0661 222 002",
                            ReturnRate = 18m,
                            RiskLevel = 1,
                            RiskScore = 54,
                            Segment = 1,
                            TotalOrders = 6,
                            TotalRevenue = 42000m,
                            Wilaya = 31
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000003"),
                            City = "Constantine",
                            CreatedAt = new DateTime(2026, 4, 3, 17, 51, 21, 893, DateTimeKind.Utc).AddTicks(9880),
                            FullName = "Fatima Zerhouni",
                            IsBlacklisted = false,
                            LastOrderDate = new DateTime(2026, 4, 5, 17, 51, 21, 893, DateTimeKind.Utc).AddTicks(9880),
                            Phone = "+213 0770 333 003",
                            ReturnRate = 0m,
                            RiskLevel = 0,
                            RiskScore = 0,
                            Segment = 0,
                            TotalOrders = 1,
                            TotalRevenue = 3500m,
                            Wilaya = 25
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000004"),
                            BlacklistReason = "Taux de retour élevé",
                            BlacklistedAt = new DateTime(2026, 3, 29, 17, 51, 21, 893, DateTimeKind.Utc).AddTicks(9880),
                            BlacklistedBy = "SuperAdmin",
                            City = "Sétif",
                            CreatedAt = new DateTime(2025, 9, 25, 17, 51, 21, 893, DateTimeKind.Utc).AddTicks(9880),
                            Email = "youcef@example.com",
                            FullName = "Youcef Mebarki",
                            IsBlacklisted = true,
                            LastOrderDate = new DateTime(2026, 2, 27, 17, 51, 21, 893, DateTimeKind.Utc).AddTicks(9880),
                            Phone = "+213 0555 444 004",
                            ReturnRate = 30m,
                            RiskLevel = 2,
                            RiskScore = 90,
                            Segment = 3,
                            TotalOrders = 3,
                            TotalRevenue = 18000m,
                            Wilaya = 19
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000005"),
                            City = "Blida",
                            CreatedAt = new DateTime(2025, 6, 17, 17, 51, 21, 893, DateTimeKind.Utc).AddTicks(9880),
                            FullName = "Nadia Boudiaf",
                            IsBlacklisted = false,
                            LastOrderDate = new DateTime(2026, 1, 3, 17, 51, 21, 893, DateTimeKind.Utc).AddTicks(9880),
                            Phone = "+213 0660 555 005",
                            ReturnRate = 8m,
                            RiskLevel = 0,
                            RiskScore = 24,
                            Segment = 4,
                            TotalOrders = 4,
                            TotalRevenue = 22000m,
                            Wilaya = 9
                        });
                });

            modelBuilder.Entity("engine_b.Modules.CRM.Domain.CustomerInteraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CustomerId");

                    b.ToTable("customer_interactions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000001"),
                            Content = "Client VIP — a appelé pour confirmer sa commande #10040. Livraison OK.",
                            CreatedAt = new DateTime(2026, 4, 11, 17, 51, 21, 895, DateTimeKind.Utc).AddTicks(4772),
                            CreatedBy = "CRM Agent",
                            CustomerId = new Guid("c1000000-0000-0000-0000-000000000001"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000002"),
                            Content = "Message WhatsApp envoyé au client pour suivi du ticket #TKT-0881.",
                            CreatedAt = new DateTime(2026, 4, 10, 17, 51, 21, 895, DateTimeKind.Utc).AddTicks(4772),
                            CreatedBy = "CRM Agent",
                            CustomerId = new Guid("c1000000-0000-0000-0000-000000000002"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000003"),
                            Content = "Premier contact client — bien reçu la commande, très satisfaite.",
                            CreatedAt = new DateTime(2026, 4, 5, 17, 51, 21, 895, DateTimeKind.Utc).AddTicks(4772),
                            CreatedBy = "SuperAdmin",
                            CustomerId = new Guid("c1000000-0000-0000-0000-000000000003"),
                            Type = 3
                        });
                });

            modelBuilder.Entity("engine_b.Modules.CRM.Domain.SupportTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedAgentName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastActionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("RelatedOrderId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Status");

                    b.HasIndex("TicketNumber")
                        .IsUnique();

                    b.ToTable("support_tickets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000001"),
                            AssignedAgentName = "CRM Agent",
                            CreatedAt = new DateTime(2026, 4, 10, 17, 51, 21, 893, DateTimeKind.Utc).AddTicks(9880),
                            CustomerId = new Guid("c1000000-0000-0000-0000-000000000002"),
                            LastActionAt = new DateTime(2026, 4, 11, 17, 51, 21, 893, DateTimeKind.Utc).AddTicks(9880),
                            Priority = 1,
                            RelatedOrderId = "#10043",
                            Status = 0,
                            Subject = "Produit endommagé à la livraison",
                            TicketNumber = "#TKT-0881",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000002"),
                            AssignedAgentName = "Non assigné",
                            CreatedAt = new DateTime(2026, 4, 6, 17, 51, 21, 893, DateTimeKind.Utc).AddTicks(9880),
                            CustomerId = new Guid("c1000000-0000-0000-0000-000000000004"),
                            LastActionAt = new DateTime(2026, 4, 7, 17, 51, 21, 893, DateTimeKind.Utc).AddTicks(9880),
                            Priority = 2,
                            RelatedOrderId = "#10039",
                            Status = 3,
                            Subject = "Demande de remboursement commande #10039",
                            TicketNumber = "#TKT-0882",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000003"),
                            AssignedAgentName = "SuperAdmin",
                            CreatedAt = new DateTime(2026, 3, 29, 17, 51, 21, 893, DateTimeKind.Utc).AddTicks(9880),
                            CustomerId = new Guid("c1000000-0000-0000-0000-000000000001"),
                            LastActionAt = new DateTime(2026, 4, 1, 17, 51, 21, 893, DateTimeKind.Utc).AddTicks(9880),
                            Priority = 3,
                            RelatedOrderId = "#10010",
                            ResolvedAt = new DateTime(2026, 4, 1, 17, 51, 21, 893, DateTimeKind.Utc).AddTicks(9880),
                            Status = 5,
                            Subject = "Question sur la garantie",
                            TicketNumber = "#TKT-0883",
                            Type = 5
                        });
                });

            modelBuilder.Entity("engine_b.Modules.Dashboard.Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ClientOrderCount")
                        .HasColumnType("integer");

                    b.Property<string>("ClientPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsNewClient")
                        .HasColumnType("boolean");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Risk")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ShippedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Wilaya")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("orders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            Amount = 4500m,
                            ClientName = "Nouveau cliente",
                            ClientOrderCount = 0,
                            ClientPhone = "+213 0550 123 456",
                            CreatedAt = new DateTime(2026, 4, 13, 16, 4, 21, 892, DateTimeKind.Utc).AddTicks(2632),
                            IsNewClient = true,
                            OrderNumber = "#10042",
                            Risk = 0,
                            Status = 1,
                            Wilaya = 16
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            Amount = 12200m,
                            ClientName = "Client régulier",
                            ClientOrderCount = 2,
                            ClientPhone = "+213 0661 987 654",
                            CreatedAt = new DateTime(2026, 4, 13, 17, 28, 21, 892, DateTimeKind.Utc).AddTicks(2632),
                            IsNewClient = false,
                            OrderNumber = "#10043",
                            Risk = 1,
                            Status = 1,
                            Wilaya = 31
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000003"),
                            Amount = 8400m,
                            ClientName = "Connu, 1 absence",
                            ClientOrderCount = 1,
                            ClientPhone = "+213 0770 456 789",
                            CreatedAt = new DateTime(2026, 4, 13, 17, 39, 21, 892, DateTimeKind.Utc).AddTicks(2632),
                            IsNewClient = false,
                            OrderNumber = "#10044",
                            Risk = 2,
                            Status = 1,
                            Wilaya = 19
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000004"),
                            Amount = 25000m,
                            ClientName = "VIP client",
                            ClientOrderCount = 15,
                            ClientPhone = "+213 0555 111 222",
                            ConfirmedAt = new DateTime(2026, 4, 13, 15, 51, 21, 892, DateTimeKind.Utc).AddTicks(2632),
                            CreatedAt = new DateTime(2026, 4, 13, 14, 51, 21, 892, DateTimeKind.Utc).AddTicks(2632),
                            IsNewClient = false,
                            OrderNumber = "#10040",
                            Risk = 0,
                            Status = 2,
                            Wilaya = 16
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000005"),
                            Amount = 6800m,
                            ClientName = "Client Oran",
                            ClientOrderCount = 5,
                            ClientPhone = "+213 0660 333 444",
                            ConfirmedAt = new DateTime(2026, 4, 13, 10, 51, 21, 892, DateTimeKind.Utc).AddTicks(2632),
                            CreatedAt = new DateTime(2026, 4, 13, 9, 51, 21, 892, DateTimeKind.Utc).AddTicks(2632),
                            DeliveredAt = new DateTime(2026, 4, 13, 16, 51, 21, 892, DateTimeKind.Utc).AddTicks(2632),
                            IsNewClient = false,
                            OrderNumber = "#10038",
                            Risk = 0,
                            ShippedAt = new DateTime(2026, 4, 13, 12, 51, 21, 892, DateTimeKind.Utc).AddTicks(2632),
                            Status = 4,
                            Wilaya = 31
                        });
                });

            modelBuilder.Entity("engine_b.Modules.Dashboard.Domain.StockAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("stock_alerts", (string)null);
                });

            modelBuilder.Entity("engine_b.Modules.Identity.Domain.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("engine_b.Modules.Identity.Domain.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("engine_b.Modules.Identity.Domain.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("engine_b.Modules.Identity.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("engine_b.Modules.Identity.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("engine_b.Modules.Identity.Domain.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("engine_b.Modules.Identity.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("engine_b.Modules.Identity.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("engine_b.Modules.CRM.Domain.CustomerInteraction", b =>
                {
                    b.HasOne("engine_b.Modules.CRM.Domain.Customer", "Customer")
                        .WithMany("Interactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("engine_b.Modules.CRM.Domain.SupportTicket", b =>
                {
                    b.HasOne("engine_b.Modules.CRM.Domain.Customer", "Customer")
                        .WithMany("Tickets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("engine_b.Modules.CRM.Domain.Customer", b =>
                {
                    b.Navigation("Interactions");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
