export const ROLES = {
  SUPERADMIN: 'SUPERADMIN', FINANCE_DIRECTOR: 'FINANCE_DIRECTOR',
  PRODUCT_MANAGER: 'PRODUCT_MANAGER', INVENTORY_MANAGER: 'INVENTORY_MANAGER',
  OMS_OPERATOR: 'OMS_OPERATOR', CRM_AGENT: 'CRM_AGENT',
  PROCUREMENT_MANAGER: 'PROCUREMENT_MANAGER', CATALOGUE_MANAGER: 'CATALOGUE_MANAGER',
  ANALYST: 'ANALYST',
}
export const ALL_ROLES      = Object.values(ROLES)
export const FIFO_ROLES     = [ROLES.SUPERADMIN, ROLES.FINANCE_DIRECTOR, ROLES.INVENTORY_MANAGER]
export const BC_APPROVAL_ROLES = [ROLES.SUPERADMIN, ROLES.FINANCE_DIRECTOR]
